import test from 'node:test';import assert from 'node:assert/strict';import {createAssemblyDiagnostics,explainAssemblyDiagnostics,diagnosticsSnapshot} from '../../src/application/cv-assembly-diagnostics.js';
const result=()=>({state:'ready',errors:[],template:{id:'classic',version:'1.0.0'},compatibility:{compatible:true,requiresReview:false},variants:{validation:{valid:true},resolved:[{selectedVariantId:'v1'}]},layout:{pageCount:2,hasOverflow:false}});
test('M1368-M1371 diagnostics summarize ready assembly',()=>{const d=createAssemblyDiagnostics(result());assert.equal(d.state,'ready');assert.equal(d.pageCount,2);});
test('M1372-M1375 diagnostics expose template identity',()=>{const d=createAssemblyDiagnostics(result());assert.equal(d.templateId,'classic');});
test('M1376-M1379 diagnostics count errors',()=>{const d=createAssemblyDiagnostics({...result(),state:'blocked',errors:['X','Y']});assert.equal(d.errorCount,2);});
test('M1380-M1383 overflow becomes diagnostic',()=>{const d=createAssemblyDiagnostics({...result(),layout:{pageCount:2,hasOverflow:true}});assert.equal(d.hasOverflow,true);});
test('M1384-M1387 compatibility state is exposed',()=>{const d=createAssemblyDiagnostics({...result(),compatibility:{compatible:false,requiresReview:true}});assert.equal(d.compatibility.compatible,false);});
test('M1388-M1391 variant validation is exposed',()=>{const d=createAssemblyDiagnostics({...result(),variants:{validation:{valid:false},resolved:[]}});assert.equal(d.variantValidationValid,false);});
test('M1392-M1395 variant count is exposed',()=>{assert.equal(createAssemblyDiagnostics(result()).variantCount,1);});
test('M1396-M1399 explanations include errors',()=>{const d=createAssemblyDiagnostics({...result(),errors:['X']});assert.ok(explainAssemblyDiagnostics(d).includes('X'));});
test('M1400-M1403 explanations include overflow',()=>{const d=createAssemblyDiagnostics({...result(),layout:{pageCount:2,hasOverflow:true}});assert.ok(explainAssemblyDiagnostics(d).some(x=>x.includes('overflow')));});
test('M1404-M1407 explanations include compatibility block',()=>{const d=createAssemblyDiagnostics({...result(),compatibility:{compatible:false}});assert.ok(explainAssemblyDiagnostics(d).some(x=>x.includes('compatibility')));});
test('M1408-M1411 explanations include variant correction',()=>{const d=createAssemblyDiagnostics({...result(),variants:{validation:{valid:false},resolved:[]}});assert.ok(explainAssemblyDiagnostics(d).some(x=>x.includes('variant')));});
test('M1412-M1415 diagnostics are read-only',()=>{assert.throws(()=>{createAssemblyDiagnostics(result()).pageCount=9},TypeError);});
test('M1416-M1419 snapshot is isolated',()=>{const d=createAssemblyDiagnostics(result());const s=diagnosticsSnapshot(d);assert.throws(()=>{s.pageCount=9},TypeError);});
test('M1420-M1423 empty errors are safe',()=>{assert.deepEqual(createAssemblyDiagnostics(result()).errors,[]);});
test('M1424-M1427 missing layout is safe',()=>{assert.equal(createAssemblyDiagnostics({...result(),layout:null}).pageCount,0);});
test('M1428-M1431 missing variants are safe',()=>{assert.equal(createAssemblyDiagnostics({...result(),variants:null}).variantCount,0);});
test('M1432-M1435 missing compatibility is blocked by projection only',()=>{assert.equal(createAssemblyDiagnostics({...result(),compatibility:null}).compatibility.compatible,false);});
test('M1436-M1439 version is stable',()=>{assert.equal(createAssemblyDiagnostics(result()).version,'1.0.0');});
test('M1440-M1447 diagnostics contract completes',()=>{const d=createAssemblyDiagnostics(result());assert.equal(d.errorCount,0);assert.equal(d.hasOverflow,false);assert.equal(explainAssemblyDiagnostics(d).length,0);});