import test from 'node:test';import assert from 'node:assert/strict';import {createLayoutState,selectLayoutBlock,moveLayoutBlock,updateLayoutBlock,validateLayoutState,snapshotLayoutState} from '../../src/application/cv-layout-state.js';
const base=()=>createLayoutState({pageModel:{format:'A4'},blocks:[{id:'a',order:0,measuredHeight:100},{id:'b',order:1,measuredHeight:200}]});
test('M1208-M1211 creates stable layout state',()=>{const s=base();assert.equal(s.version,'1.0.0');assert.equal(s.blocks.length,2);});
test('M1212-M1215 selects an existing block',()=>{assert.equal(selectLayoutBlock(base(),'b').selectedBlockId,'b');});
test('M1216-M1219 rejects missing block selection',()=>{assert.throws(()=>selectLayoutBlock(base(),'x'),/Layout block not found/)});
test('M1220-M1223 moves block order',()=>{const s=moveLayoutBlock(base(),'b',-1);assert.equal(s.blocks[0].id,'b');});
test('M1224-M1227 updates block data',()=>{const s=updateLayoutBlock(base(),'a',{measuredHeight:150});assert.equal(s.blocks[0].measuredHeight,150);});
test('M1228-M1231 rejects missing block update',()=>{assert.throws(()=>updateLayoutBlock(base(),'x',{}),/Layout block not found/)});
test('M1232-M1235 validates clean state',()=>{assert.equal(validateLayoutState(base()).valid,true);});
test('M1236-M1239 rejects duplicate ids',()=>{const s=base();s.blocks.push({id:'a'});assert.equal(validateLayoutState(s).valid,false);});
test('M1240-M1243 rejects stale selected id',()=>{const s=base();s.selectedBlockId='x';assert.equal(validateLayoutState(s).valid,false);});
test('M1244-M1247 snapshots are isolated',()=>{const s=base();const snap=snapshotLayoutState(s);assert.throws(()=>{snap.revision=9},TypeError);});
test('M1248-M1251 mutations advance revision',()=>{assert.ok(selectLayoutBlock(base(),'a').revision>1);});
test('M1252-M1255 order mutation preserves blocks',()=>{assert.equal(moveLayoutBlock(base(),'a',3).blocks.length,2);});
test('M1256-M1259 patch is isolated',()=>{const s=updateLayoutBlock(base(),'a',{metadata:{x:1}});s.blocks[0].metadata.x=2;assert.equal(base().blocks[0].metadata,undefined);});
test('M1260-M1263 selection can clear',()=>{assert.equal(selectLayoutBlock(selectLayoutBlock(base(),'a'),null).selectedBlockId,null);});
test('M1264-M1267 page model survives mutation',()=>{assert.equal(selectLayoutBlock(base(),'a').pageModel.format,'A4');});
test('M1268-M1271 layout version is explicit',()=>{assert.equal(base().version,'1.0.0');});
test('M1272-M1275 validation requires array',()=>{const s=base();s.blocks=null;assert.equal(validateLayoutState(s).valid,false);});
test('M1276-M1279 state timestamps update',()=>{assert.ok(moveLayoutBlock(base(),'a',2).updatedAt);});
test('M1280-M1287 layout contract completes',()=>{const s=moveLayoutBlock(updateLayoutBlock(selectLayoutBlock(base(),'a'),'a',{measuredHeight:120}), 'b',-1);assert.equal(validateLayoutState(s).valid,true);});