import test from 'node:test';import assert from 'node:assert/strict';import {createTemplateRegistry} from '../../src/templates/template-engine.js';import {resolveTemplateSelection,validateTemplateSelection,applyTemplateSelection} from '../../src/application/cv-template-selection.js';
const registry=()=>createTemplateRegistry([{id:'classic',name:'Classic',status:'published'},{id:'modern',name:'Modern',status:'published'}]);
test('M1128-M1131 requested template is selected',()=>{const r=registry();const s=resolveTemplateSelection(r,'modern');assert.equal(s.templateId,'modern');assert.equal(s.source,'requested');});
test('M1132-M1135 fallback is deterministic',()=>{const r=registry();const s=resolveTemplateSelection(r,'missing');assert.equal(s.templateId,'classic');assert.equal(s.fallbackUsed,true);});
test('M1136-M1139 missing registry is rejected',()=>{assert.throws(()=>resolveTemplateSelection(null,'x'),/Template registry/)});
test('M1140-M1143 validation accepts registered selection',()=>{const r=registry();const s=resolveTemplateSelection(r,'classic');assert.equal(validateTemplateSelection(r,s).valid,true);});
test('M1144-M1147 validation rejects missing selection',()=>{assert.equal(validateTemplateSelection(registry(),{}).valid,false);});
test('M1148-M1151 validation rejects unknown selection',()=>{assert.equal(validateTemplateSelection(registry(),{templateId:'x'}).valid,false);});
test('M1152-M1155 configuration application preserves selection identity',()=>{const r=registry();const s=resolveTemplateSelection(r,'modern');const c=applyTemplateSelection({},s);assert.equal(c.template.id,'modern');});
test('M1156-M1159 applied configuration is isolated',()=>{const r=registry();const s=resolveTemplateSelection(r,'modern');const c=applyTemplateSelection({},s);c.template.id='x';assert.equal(s.templateId,'modern');});
test('M1160-M1163 selection state is immutable',()=>{const s=resolveTemplateSelection(registry(),'classic');assert.throws(()=>{s.templateId='x'},TypeError);});
test('M1164-M1167 published filtering can constrain fallback',()=>{const r=createTemplateRegistry([{id:'draft',name:'Draft',status:'draft'},{id:'pub',name:'Pub',status:'published'}]);const s=resolveTemplateSelection(r,null,{status:'published'});assert.equal(s.templateId,'pub');});
test('M1168-M1171 no template fails explicitly',()=>{assert.throws(()=>resolveTemplateSelection(createTemplateRegistry(),null),/No template/);});
test('M1172-M1175 selection records source',()=>{const s=resolveTemplateSelection(registry(),'classic');assert.equal(s.source,'requested');});
test('M1176-M1179 selection version is stable',()=>{const s=resolveTemplateSelection(registry(),'classic');assert.equal(s.version,'1.0.0');});
test('M1180-M1183 applied config carries selection version',()=>{const s=resolveTemplateSelection(registry(),'classic');assert.equal(applyTemplateSelection({},s).template.selectionVersion,'1.0.0');});
test('M1184-M1187 repeated resolution is stable',()=>{const r=registry();assert.equal(resolveTemplateSelection(r,'classic').templateId,resolveTemplateSelection(r,'classic').templateId);});
test('M1188-M1191 fallback remains explicit',()=>{const s=resolveTemplateSelection(registry(),'missing');assert.equal(s.source,'fallback');});
test('M1192-M1195 unknown selection remains invalid',()=>{const r=registry();assert.equal(validateTemplateSelection(r,{templateId:'missing'}).errors.length,1);});
test('M1196-M1199 selection contract completes',()=>{const r=registry();const s=resolveTemplateSelection(r,'modern');assert.ok(s.templateId);assert.equal(validateTemplateSelection(r,s).valid,true);});
test('M1200-M1207 template boundary is independent from rendering',()=>{const r=registry();const s=resolveTemplateSelection(r,'classic');const c=applyTemplateSelection({presentation:{}},s);assert.equal(c.template.id,'classic');assert.deepEqual(c.presentation,{});});