import test from 'node:test';import assert from 'node:assert/strict';import {createPreviewController} from '../../src/application/cv-preview-controller.js';
test('M1288-M1291 initializes preview state',()=>{const c=createPreviewController({pageCount:3});assert.equal(c.getState().currentPage,1);});
test('M1292-M1295 applies preview result',()=>{const c=createPreviewController();const s=c.setResult({status:'ready',pageCount:4,requestId:'r1'});assert.equal(s.pageCount,4);});
test('M1296-M1299 next page is bounded',()=>{const c=createPreviewController({pageCount:2});assert.equal(c.nextPage().currentPage,2);assert.equal(c.nextPage().currentPage,2);});
test('M1300-M1303 previous page is bounded',()=>{const c=createPreviewController({pageCount:2});c.nextPage();assert.equal(c.previousPage().currentPage,1);assert.equal(c.previousPage().currentPage,1);});
test('M1304-M1307 direct page selection clamps',()=>{const c=createPreviewController({pageCount:3});assert.equal(c.setPage(9).currentPage,3);});
test('M1308-M1311 zoom clamps',()=>{const c=createPreviewController();assert.equal(c.setZoom(9).zoom,4);assert.equal(c.setZoom(.01).zoom,.25);});
test('M1312-M1315 state is read-only',()=>{const c=createPreviewController();assert.throws(()=>{c.getState().zoom=2},TypeError);});
test('M1316-M1319 result clamps existing page',()=>{const c=createPreviewController({pageCount:4});c.setPage(4);assert.equal(c.setResult({status:'ready',pageCount:2}).currentPage,2);});
test('M1320-M1323 request identity is retained',()=>{const c=createPreviewController();assert.equal(c.setResult({pageCount:1,requestId:'x'}).requestId,'x');});
test('M1324-M1327 destroyed controller fences mutation',()=>{const c=createPreviewController();c.destroy();assert.equal(c.nextPage(),null);});
test('M1328-M1331 destroyed page selection is fenced',()=>{const c=createPreviewController();c.destroy();assert.equal(c.setPage(2),null);});
test('M1332-M1335 destroyed zoom is fenced',()=>{const c=createPreviewController();c.destroy();assert.equal(c.setZoom(2),null);});
test('M1336-M1339 controller version is stable',()=>{assert.equal(createPreviewController().getState().version,'1.0.0');});
test('M1340-M1343 empty preview has page one boundary',()=>{assert.equal(createPreviewController().nextPage().currentPage,1);});
test('M1344-M1347 result status is exposed',()=>{assert.equal(createPreviewController().setResult({status:'ready',pageCount:1}).status,'ready');});
test('M1348-M1351 zoom persists across page changes',()=>{const c=createPreviewController({pageCount:2});c.setZoom(2);c.nextPage();assert.equal(c.getState().zoom,2);});
test('M1352-M1355 direct page preserves zoom',()=>{const c=createPreviewController({pageCount:2});c.setZoom(2);c.setPage(2);assert.equal(c.getState().zoom,2);});
test('M1356-M1359 repeated result replacement is safe',()=>{const c=createPreviewController();c.setResult({pageCount:3});c.setResult({pageCount:1});assert.equal(c.getState().pageCount,1);});
test('M1360-M1367 preview controller contract completes',()=>{const c=createPreviewController({pageCount:3});c.setResult({status:'ready',pageCount:3,requestId:'done'});c.nextPage();assert.equal(c.getState().currentPage,2);});